// Pedalboard presentation and drag targets. Patch mutations go through the command adapter.
import { Fragment, useMemo, useRef, useLayoutEffect } from 'react';
import type { Rig, Slot } from './types';
export function Board({ rig, selected }: { rig: Rig; selected: string | null }) {
  const slots = window.SlotBoard.slots(rig);
  const positions = useRef(new Map<string, DOMRect>());
  useLayoutEffect(() => {
    const next = new Map<string, DOMRect>(),
      reduced = matchMedia('(prefers-reduced-motion: reduce)').matches;
    document.querySelectorAll<HTMLElement>('.react-board [data-block]').forEach((item) => {
      if (!item.getClientRects().length) return;
      const rect = item.parentElement!.getBoundingClientRect(),
        id = item.dataset.block!,
        old = positions.current.get(id);
      next.set(id, rect);
      if (old && !reduced) {
        const x = old.left - rect.left,
          y = old.top - rect.top;
        if (Math.abs(x) + Math.abs(y) > 2 && Math.abs(x) < innerWidth && Math.abs(y) < innerHeight)
          item.animate(
            [{ transform: `translate(${x}px,${y}px)` }, { transform: 'translate(0,0)' }],
            { duration: 180, easing: 'cubic-bezier(.2,.7,.3,1)' },
          );
      }
    });
    positions.current = next;
  });

  const cards = (section: string, stack = false) => {
    const all = slots.filter((x) => x.section === section);
    const used = all.filter((x) => x.block);
    return (stack ? (used.length ? used : all.slice(0, 1)) : all).map((slot) => (
      <Card
        key={slot.block?.id || `${section}:${slot.index}`}
        slot={slot}
        rig={rig}
        selected={selected}
      />
    ));
  };
  return (
    <div className="pedalboard react-board">
      <div className="board-flow" aria-label="Signal order">
        {['INPUT', '1 Before amp', '2 Amp', '3 FX loop', '4 Cab', '5 After cab', 'OUTPUT'].map(
          (label, i) => (
            <Fragment key={label}>
              {i > 0 && <b>→</b>}
              <span>{label}</span>
            </Fragment>
          ),
        )}
      </div>
      <div className="amp-cab-shelf">
        <section className="stack-stage">
          <header>
            <span className="stage-number">2</span>
            <h3>Amplifier</h3>
          </header>
          <div className="stack-devices">{cards('amp', true)}</div>
        </section>
        <div className="loop-link">
          SEND <span>↓ FX LOOP ↑</span> RETURN
        </div>
        <section className="stack-stage">
          <header>
            <span className="stage-number">4</span>
            <h3>Cabinets</h3>
            {slots.filter((s) => s.section === 'cab' && s.block).length > 1 && (
              <small>PARALLEL · SUMMED</small>
            )}
          </header>
          <div className="stack-devices">{cards('cab', true)}</div>
        </section>
      </div>
      <div className="pedal-deck">
        {[
          ['pre', 1, 'Before amp', 'Guitar → pedals → amp'],
          ['loop', 3, 'Amp FX loop', 'Amp → effects → cabinets'],
          ['post', 5, 'After cab', 'Cabinets → effects → output'],
        ].map(([section, num, title, detail]) => (
          <section className="pedal-row" key={section}>
            <header>
              <span className="stage-number">{num}</span>
              <div>
                <h3>{title}</h3>
                <p>{detail}</p>
              </div>
            </header>
            <div className="pedal-slots">{cards(String(section))}</div>
          </section>
        ))}
      </div>
    </div>
  );
}
// SVG artwork is generated by the existing, escaped illustration renderer.
function Artwork({ block, on }: { block: Rig['blocks'][number]; on: boolean }) {
  const html = useMemo(
    () => window.GearLooks.art(block, on),
    [block.key, block.appearance?.style, block.appearance?.colour, on],
  );
  return <span className="react-art" dangerouslySetInnerHTML={{ __html: html }} />;
}

function Card({ slot, rig, selected }: { slot: Slot; rig: Rig; selected: string | null }) {
  const block = slot.block;
  if (!block)
    return (
      <button
        className="board-empty"
        data-slot={`${slot.section}:${slot.index}`}
        aria-label={`Add device: ${window.SlotBoard.label(slot)}`}
      >
        <span>＋</span>
        <small>{window.SlotBoard.label(slot)}</small>
      </button>
    );
  const d = window.DeviceShelf.definition(block),
    on = rig.scenes[rig.scene][block.id].on;
  return (
    <div className={'board-card ' + (selected === block.id ? 'selected' : '')}>
      <button
        className={'board-gear ' + (on ? '' : 'bypassed')}
        data-block={block.id}
        aria-label={`Edit ${d.name}`}
        aria-pressed={selected === block.id}
      >
        <Artwork block={block} on={on} />
        <span>
          <strong>{d.name}</strong>
          <small>{window.SlotBoard.label(slot)}</small>
        </span>
      </button>
      <button
        className="board-bypass"
        data-node-bypass={block.id}
        aria-label={`${on ? 'Bypass' : 'Enable'} ${d.name}`}
        aria-pressed={!on}
      >
        {on ? '●' : '○'}
      </button>
    </div>
  );
}
