// GENERATED by scripts/import-airwindows.mjs from the curated manifest.
#include "effects_air_import.h"
#include "vendor/airwindows/autogen_airwin/Parametric.h"
#include "vendor/airwindows/autogen_airwin/PearEQ.h"
#include "vendor/airwindows/autogen_airwin/Baxandall2.h"
#include "vendor/airwindows/autogen_airwin/SmoothEQ3.h"
#include "vendor/airwindows/autogen_airwin/ToneSlant.h"
#include "vendor/airwindows/autogen_airwin/EQ.h"
#include "vendor/airwindows/autogen_airwin/Hull2.h"
#include "vendor/airwindows/autogen_airwin/BiquadStack.h"
#include "vendor/airwindows/autogen_airwin/ResEQ.h"
#include "vendor/airwindows/autogen_airwin/Air4.h"
#include "vendor/airwindows/autogen_airwin/Energy2.h"
#include "vendor/airwindows/autogen_airwin/Stonefire.h"
#include "vendor/airwindows/autogen_airwin/Weight.h"
#include "vendor/airwindows/autogen_airwin/SubTight.h"
#include "vendor/airwindows/autogen_airwin/AngleFilter.h"
#include "vendor/airwindows/autogen_airwin/Aura.h"
#include "vendor/airwindows/autogen_airwin/BiquadPlus.h"
#include "vendor/airwindows/autogen_airwin/BiquadHiLo.h"
#include "vendor/airwindows/autogen_airwin/BiquadNonLin.h"
#include "vendor/airwindows/autogen_airwin/Capacitor2.h"
#include "vendor/airwindows/autogen_airwin/Dattorro.h"
#include "vendor/airwindows/autogen_airwin/Donut.h"
#include "vendor/airwindows/autogen_airwin/Holt2.h"
#include "vendor/airwindows/autogen_airwin/Isolator3.h"
#include "vendor/airwindows/autogen_airwin/Suzan.h"
#include "vendor/airwindows/autogen_airwin/XRegion.h"
#include "vendor/airwindows/autogen_airwin/YLowpass.h"
#include "vendor/airwindows/autogen_airwin/ZAcidLowpass.h"
#include "vendor/airwindows/autogen_airwin/ZBandpass2.h"
#include "vendor/airwindows/autogen_airwin/ZHighpass2.h"
#include "vendor/airwindows/autogen_airwin/ZNotch2.h"
#include "vendor/airwindows/autogen_airwin/ZRegion2.h"
#include "vendor/airwindows/autogen_airwin/Hermepass.h"
#include "vendor/airwindows/autogen_airwin/Infrasonic.h"
#include "vendor/airwindows/autogen_airwin/BeziComp.h"
#include "vendor/airwindows/autogen_airwin/BlockParty.h"
#include "vendor/airwindows/autogen_airwin/ButterComp2.h"
#include "vendor/airwindows/autogen_airwin/Compresaturator.h"
#include "vendor/airwindows/autogen_airwin/DigitalBlack.h"
#include "vendor/airwindows/autogen_airwin/Dynamics3.h"
#include "vendor/airwindows/autogen_airwin/Gatelope.h"
#include "vendor/airwindows/autogen_airwin/Logical4.h"
#include "vendor/airwindows/autogen_airwin/Overheads.h"
#include "vendor/airwindows/autogen_airwin/Point.h"
#include "vendor/airwindows/autogen_airwin/Pop3.h"
#include "vendor/airwindows/autogen_airwin/Pressure4.h"
#include "vendor/airwindows/autogen_airwin/PurestSquish.h"
#include "vendor/airwindows/autogen_airwin/Pyewacket.h"
#include "vendor/airwindows/autogen_airwin/Recurve.h"
#include "vendor/airwindows/autogen_airwin/SoftGate.h"
#include "vendor/airwindows/autogen_airwin/StoneFireComp.h"
#include "vendor/airwindows/autogen_airwin/SurgeTide.h"
#include "vendor/airwindows/autogen_airwin/Swell.h"
#include "vendor/airwindows/autogen_airwin/Thunder.h"
#include "vendor/airwindows/autogen_airwin/VariMu.h"
#include "vendor/airwindows/autogen_airwin/DeBess.h"
#include "vendor/airwindows/autogen_airwin/DeHiss.h"
#include "vendor/airwindows/autogen_airwin/DeNoise.h"
#include "vendor/airwindows/autogen_airwin/Density3.h"
#include "vendor/airwindows/autogen_airwin/Dirt.h"
#include "vendor/airwindows/autogen_airwin/Distortion.h"
#include "vendor/airwindows/autogen_airwin/Drive.h"
#include "vendor/airwindows/autogen_airwin/Edge.h"
#include "vendor/airwindows/autogen_airwin/HardVacuum.h"
#include "vendor/airwindows/autogen_airwin/HighImpact.h"
#include "vendor/airwindows/autogen_airwin/Mackity.h"
#include "vendor/airwindows/autogen_airwin/MultiBandDistortion.h"
#include "vendor/airwindows/autogen_airwin/PurestDrive.h"
#include "vendor/airwindows/autogen_airwin/Spiral2.h"
#include "vendor/airwindows/autogen_airwin/Tube2.h"
#include "vendor/airwindows/autogen_airwin/UnBox.h"
#include "vendor/airwindows/autogen_airwin/Coils2.h"
#include "vendor/airwindows/autogen_airwin/Creature.h"
#include "vendor/airwindows/autogen_airwin/Focus.h"
#include "vendor/airwindows/autogen_airwin/Fracture2.h"
#include "vendor/airwindows/autogen_airwin/Gringer.h"
#include "vendor/airwindows/autogen_airwin/GuitarConditioner.h"
#include "vendor/airwindows/autogen_airwin/PowerSag2.h"
#include "vendor/airwindows/autogen_airwin/SingleEndedTriode.h"
#include "vendor/airwindows/autogen_airwin/Inflamer.h"
#include "vendor/airwindows/autogen_airwin/Sweeten.h"
#include "vendor/airwindows/autogen_airwin/BussColors4.h"
#include "vendor/airwindows/autogen_airwin/Channel9.h"
#include "vendor/airwindows/autogen_airwin/CStrip2.h"
#include "vendor/airwindows/autogen_airwin/Desk4.h"
#include "vendor/airwindows/autogen_airwin/Discontapeity.h"
#include "vendor/airwindows/autogen_airwin/Discontinuity.h"
#include "vendor/airwindows/autogen_airwin/PurestWarm3.h"
#include "vendor/airwindows/autogen_airwin/Exciter.h"
#include "vendor/airwindows/autogen_airwin/Acceleration2.h"
#include "vendor/airwindows/autogen_airwin/GoldenSlew.h"
#include "vendor/airwindows/autogen_airwin/Slew4.h"
#include "vendor/airwindows/autogen_airwin/Smooth.h"
#include "vendor/airwindows/autogen_airwin/Remap.h"
#include "vendor/airwindows/autogen_airwin/WoodenBox.h"
#include "vendor/airwindows/autogen_airwin/BitGlitter.h"
#include "vendor/airwindows/autogen_airwin/Bite.h"
#include "vendor/airwindows/autogen_airwin/ChromeOxide.h"
#include "vendor/airwindows/autogen_airwin/Cojones.h"
#include "vendor/airwindows/autogen_airwin/CrunchyGrooveWear.h"
#include "vendor/airwindows/autogen_airwin/DeBez.h"
#include "vendor/airwindows/autogen_airwin/DeRez3.h"
#include "vendor/airwindows/autogen_airwin/Deckwrecka.h"
#include "vendor/airwindows/autogen_airwin/Dubly3.h"
#include "vendor/airwindows/autogen_airwin/Flutter2.h"
#include "vendor/airwindows/autogen_airwin/GrooveWear.h"
#include "vendor/airwindows/autogen_airwin/HipCrush.h"
#include "vendor/airwindows/autogen_airwin/Pockey2.h"
#include "vendor/airwindows/autogen_airwin/TapeBias.h"
#include "vendor/airwindows/autogen_airwin/TapeDust.h"
#include "vendor/airwindows/autogen_airwin/Texturize.h"
#include "vendor/airwindows/autogen_airwin/ToVinyl4.h"
#include "vendor/airwindows/autogen_airwin/FromTape.h"
#include "vendor/airwindows/autogen_airwin/IronOxideClassic2.h"
#include "vendor/airwindows/autogen_airwin/Tape.h"
#include "vendor/airwindows/autogen_airwin/ToTape8.h"
#include "vendor/airwindows/autogen_airwin/TapeHack2.h"
#include "vendor/airwindows/autogen_airwin/Ensemble.h"
#include "vendor/airwindows/autogen_airwin/GalacticVibe.h"
#include "vendor/airwindows/autogen_airwin/Melt.h"
#include "vendor/airwindows/autogen_airwin/TremoSquare.h"
#include "vendor/airwindows/autogen_airwin/RingModulator.h"
#include "vendor/airwindows/autogen_airwin/GlitchShifter.h"
#include "vendor/airwindows/autogen_airwin/PitchNasty.h"
#include "vendor/airwindows/autogen_airwin/StereoDoubler.h"
#include "vendor/airwindows/autogen_airwin/TripleSpread.h"
#include "vendor/airwindows/autogen_airwin/FathomFive.h"
#include "vendor/airwindows/autogen_airwin/DubSub.h"
#include "vendor/airwindows/autogen_airwin/Srsly3.h"
#include "vendor/airwindows/autogen_airwin/StereoFX.h"
#include "vendor/airwindows/autogen_airwin/SweetWide.h"
#include "vendor/airwindows/autogen_airwin/Wider.h"
#include "vendor/airwindows/autogen_airwin/Sidepass.h"
#include "vendor/airwindows/autogen_airwin/SideDull.h"
#include "vendor/airwindows/autogen_airwin/ADT.h"
#include "vendor/airwindows/autogen_airwin/Hombre.h"
#include "vendor/airwindows/autogen_airwin/StarChild2.h"
#include "vendor/airwindows/autogen_airwin/kChamberAR.h"
#include "vendor/airwindows/autogen_airwin/BrightAmbience3.h"
#include "vendor/airwindows/autogen_airwin/Chamber2.h"
#include "vendor/airwindows/autogen_airwin/CrunchCoat.h"
#include "vendor/airwindows/autogen_airwin/Infinity2.h"
#include "vendor/airwindows/autogen_airwin/MatrixVerb.h"
#include "vendor/airwindows/autogen_airwin/MV2.h"
#include "vendor/airwindows/autogen_airwin/NonlinearSpace.h"
#include "vendor/airwindows/autogen_airwin/PocketVerbs.h"
#include "vendor/airwindows/autogen_airwin/Ultralight2.h"
#include "vendor/airwindows/autogen_airwin/Verbity2.h"
#include "vendor/airwindows/autogen_airwin/kAlienSpaceship.h"
#include "vendor/airwindows/autogen_airwin/kCosmos.h"
#include "vendor/airwindows/autogen_airwin/kCyberCity.h"
#include "vendor/airwindows/autogen_airwin/kPlate140.h"
#include "vendor/airwindows/autogen_airwin/kPlate240.h"
#include "vendor/airwindows/autogen_airwin/kRockstar.h"
#include "vendor/airwindows/autogen_airwin/kStation.h"
#include "vendor/airwindows/autogen_airwin/kWoodRoom.h"
std::unique_ptr<Effect> makeImportedAir(const std::string &key, int rate)
{
    if (key == "Parametric")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::Parametric::Parametric(0),
            airwinconsolidated::Parametric::kNumParameters, rate, 0);
    if (key == "PearEQ")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::PearEQ::PearEQ(0),
                                                   airwinconsolidated::PearEQ::kNumParameters, rate,
                                                   0);
    if (key == "Baxandall2")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::Baxandall2::Baxandall2(0),
            airwinconsolidated::Baxandall2::kNumParameters, rate, 0);
    if (key == "SmoothEQ3")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::SmoothEQ3::SmoothEQ3(0),
                                                   airwinconsolidated::SmoothEQ3::kNumParameters,
                                                   rate, 0);
    if (key == "ToneSlant")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::ToneSlant::ToneSlant(0),
                                                   airwinconsolidated::ToneSlant::kNumParameters,
                                                   rate, 0);
    if (key == "EQ")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::EQ::EQ(0),
                                                   airwinconsolidated::EQ::kNumParameters, rate, 0);
    if (key == "Hull2")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Hull2::Hull2(0),
                                                   airwinconsolidated::Hull2::kNumParameters, rate,
                                                   0);
    if (key == "BiquadStack")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::BiquadStack::BiquadStack(0),
            airwinconsolidated::BiquadStack::kNumParameters, rate, 0);
    if (key == "ResEQ")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::ResEQ::ResEQ(0),
                                                   airwinconsolidated::ResEQ::kNumParameters, rate,
                                                   0);
    if (key == "Air4")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Air4::Air4(0),
                                                   airwinconsolidated::Air4::kNumParameters, rate,
                                                   0);
    if (key == "Energy2")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Energy2::Energy2(0),
                                                   airwinconsolidated::Energy2::kNumParameters,
                                                   rate, 0);
    if (key == "Stonefire")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Stonefire::Stonefire(0),
                                                   airwinconsolidated::Stonefire::kNumParameters,
                                                   rate, 0);
    if (key == "Weight")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Weight::Weight(0),
                                                   airwinconsolidated::Weight::kNumParameters, rate,
                                                   0);
    if (key == "SubTight")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::SubTight::SubTight(0),
                                                   airwinconsolidated::SubTight::kNumParameters,
                                                   rate, 0);
    if (key == "AngleFilter")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::AngleFilter::AngleFilter(0),
            airwinconsolidated::AngleFilter::kNumParameters, rate, 0);
    if (key == "Aura")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Aura::Aura(0),
                                                   airwinconsolidated::Aura::kNumParameters, rate,
                                                   0);
    if (key == "BiquadPlus")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::BiquadPlus::BiquadPlus(0),
            airwinconsolidated::BiquadPlus::kNumParameters, rate, 0);
    if (key == "BiquadHiLo")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::BiquadHiLo::BiquadHiLo(0),
            airwinconsolidated::BiquadHiLo::kNumParameters, rate, 0);
    if (key == "BiquadNonLin")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::BiquadNonLin::BiquadNonLin(0),
            airwinconsolidated::BiquadNonLin::kNumParameters, rate, 0);
    if (key == "Capacitor2")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::Capacitor2::Capacitor2(0),
            airwinconsolidated::Capacitor2::kNumParameters, rate, 0);
    if (key == "Dattorro")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Dattorro::Dattorro(0),
                                                   airwinconsolidated::Dattorro::kNumParameters,
                                                   rate, 0);
    if (key == "Donut")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Donut::Donut(0),
                                                   airwinconsolidated::Donut::kNumParameters, rate,
                                                   0);
    if (key == "Holt2")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Holt2::Holt2(0),
                                                   airwinconsolidated::Holt2::kNumParameters, rate,
                                                   0);
    if (key == "Isolator3")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Isolator3::Isolator3(0),
                                                   airwinconsolidated::Isolator3::kNumParameters,
                                                   rate, 1);
    if (key == "Suzan")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Suzan::Suzan(0),
                                                   airwinconsolidated::Suzan::kNumParameters, rate,
                                                   0);
    if (key == "XRegion")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::XRegion::XRegion(0),
                                                   airwinconsolidated::XRegion::kNumParameters,
                                                   rate, 0);
    if (key == "YLowpass")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::YLowpass::YLowpass(0),
                                                   airwinconsolidated::YLowpass::kNumParameters,
                                                   rate, 0);
    if (key == "ZAcidLowpass")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::ZAcidLowpass::ZAcidLowpass(0),
            airwinconsolidated::ZAcidLowpass::kNumParameters, rate, 0);
    if (key == "ZBandpass2")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::ZBandpass2::ZBandpass2(0),
            airwinconsolidated::ZBandpass2::kNumParameters, rate, 0);
    if (key == "ZHighpass2")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::ZHighpass2::ZHighpass2(0),
            airwinconsolidated::ZHighpass2::kNumParameters, rate, 0);
    if (key == "ZNotch2")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::ZNotch2::ZNotch2(0),
                                                   airwinconsolidated::ZNotch2::kNumParameters,
                                                   rate, 0);
    if (key == "ZRegion2")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::ZRegion2::ZRegion2(0),
                                                   airwinconsolidated::ZRegion2::kNumParameters,
                                                   rate, 0);
    if (key == "Hermepass")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Hermepass::Hermepass(0),
                                                   airwinconsolidated::Hermepass::kNumParameters,
                                                   rate, 0);
    if (key == "Infrasonic")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::Infrasonic::Infrasonic(0),
            airwinconsolidated::Infrasonic::kNumParameters, rate, 0);
    if (key == "BeziComp")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::BeziComp::BeziComp(0),
                                                   airwinconsolidated::BeziComp::kNumParameters,
                                                   rate, 1);
    if (key == "BlockParty")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::BlockParty::BlockParty(0),
            airwinconsolidated::BlockParty::kNumParameters, rate, 0);
    if (key == "ButterComp2")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::ButterComp2::ButterComp2(0),
            airwinconsolidated::ButterComp2::kNumParameters, rate, 0);
    if (key == "Compresaturator")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::Compresaturator::Compresaturator(0),
            airwinconsolidated::Compresaturator::kNumParameters, rate, 0);
    if (key == "DigitalBlack")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::DigitalBlack::DigitalBlack(0),
            airwinconsolidated::DigitalBlack::kNumParameters, rate, 0);
    if (key == "Dynamics3")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Dynamics3::Dynamics3(0),
                                                   airwinconsolidated::Dynamics3::kNumParameters,
                                                   rate, 0);
    if (key == "Gatelope")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Gatelope::Gatelope(0),
                                                   airwinconsolidated::Gatelope::kNumParameters,
                                                   rate, 0);
    if (key == "Logical4")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Logical4::Logical4(0),
                                                   airwinconsolidated::Logical4::kNumParameters,
                                                   rate, 0);
    if (key == "Overheads")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Overheads::Overheads(0),
                                                   airwinconsolidated::Overheads::kNumParameters,
                                                   rate, 0);
    if (key == "Point")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Point::Point(0),
                                                   airwinconsolidated::Point::kNumParameters, rate,
                                                   0);
    if (key == "Pop3")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Pop3::Pop3(0),
                                                   airwinconsolidated::Pop3::kNumParameters, rate,
                                                   0);
    if (key == "Pressure4")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Pressure4::Pressure4(0),
                                                   airwinconsolidated::Pressure4::kNumParameters,
                                                   rate, 0);
    if (key == "PurestSquish")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::PurestSquish::PurestSquish(0),
            airwinconsolidated::PurestSquish::kNumParameters, rate, 0);
    if (key == "Pyewacket")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Pyewacket::Pyewacket(0),
                                                   airwinconsolidated::Pyewacket::kNumParameters,
                                                   rate, 0);
    if (key == "Recurve")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Recurve::Recurve(0),
                                                   airwinconsolidated::Recurve::kNumParameters,
                                                   rate, 0);
    if (key == "SoftGate")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::SoftGate::SoftGate(0),
                                                   airwinconsolidated::SoftGate::kNumParameters,
                                                   rate, 0);
    if (key == "StoneFireComp")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::StoneFireComp::StoneFireComp(0),
            airwinconsolidated::StoneFireComp::kNumParameters, rate, 0);
    if (key == "SurgeTide")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::SurgeTide::SurgeTide(0),
                                                   airwinconsolidated::SurgeTide::kNumParameters,
                                                   rate, 0);
    if (key == "Swell")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Swell::Swell(0),
                                                   airwinconsolidated::Swell::kNumParameters, rate,
                                                   0);
    if (key == "Thunder")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Thunder::Thunder(0),
                                                   airwinconsolidated::Thunder::kNumParameters,
                                                   rate, 0);
    if (key == "VariMu")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::VariMu::VariMu(0),
                                                   airwinconsolidated::VariMu::kNumParameters, rate,
                                                   0);
    if (key == "DeBess")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::DeBess::DeBess(0),
                                                   airwinconsolidated::DeBess::kNumParameters, rate,
                                                   0);
    if (key == "DeHiss")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::DeHiss::DeHiss(0),
                                                   airwinconsolidated::DeHiss::kNumParameters, rate,
                                                   0);
    if (key == "DeNoise")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::DeNoise::DeNoise(0),
                                                   airwinconsolidated::DeNoise::kNumParameters,
                                                   rate, 0);
    if (key == "Density3")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Density3::Density3(0),
                                                   airwinconsolidated::Density3::kNumParameters,
                                                   rate, 0);
    if (key == "Dirt")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Dirt::Dirt(0),
                                                   airwinconsolidated::Dirt::kNumParameters, rate,
                                                   0);
    if (key == "Distortion")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::Distortion::Distortion(0),
            airwinconsolidated::Distortion::kNumParameters, rate, 0);
    if (key == "Drive")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Drive::Drive(0),
                                                   airwinconsolidated::Drive::kNumParameters, rate,
                                                   0);
    if (key == "Edge")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Edge::Edge(0),
                                                   airwinconsolidated::Edge::kNumParameters, rate,
                                                   0);
    if (key == "HardVacuum")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::HardVacuum::HardVacuum(0),
            airwinconsolidated::HardVacuum::kNumParameters, rate, 0);
    if (key == "HighImpact")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::HighImpact::HighImpact(0),
            airwinconsolidated::HighImpact::kNumParameters, rate, 0);
    if (key == "Mackity")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Mackity::Mackity(0),
                                                   airwinconsolidated::Mackity::kNumParameters,
                                                   rate, 0);
    if (key == "MultiBandDistortion")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::MultiBandDistortion::MultiBandDistortion(0),
            airwinconsolidated::MultiBandDistortion::kNumParameters, rate, 0);
    if (key == "PurestDrive")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::PurestDrive::PurestDrive(0),
            airwinconsolidated::PurestDrive::kNumParameters, rate, 0);
    if (key == "Spiral2")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Spiral2::Spiral2(0),
                                                   airwinconsolidated::Spiral2::kNumParameters,
                                                   rate, 0);
    if (key == "Tube2")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Tube2::Tube2(0),
                                                   airwinconsolidated::Tube2::kNumParameters, rate,
                                                   0);
    if (key == "UnBox")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::UnBox::UnBox(0),
                                                   airwinconsolidated::UnBox::kNumParameters, rate,
                                                   0);
    if (key == "Coils2")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Coils2::Coils2(0),
                                                   airwinconsolidated::Coils2::kNumParameters, rate,
                                                   0);
    if (key == "Creature")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Creature::Creature(0),
                                                   airwinconsolidated::Creature::kNumParameters,
                                                   rate, 0);
    if (key == "Focus")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Focus::Focus(0),
                                                   airwinconsolidated::Focus::kNumParameters, rate,
                                                   0);
    if (key == "Fracture2")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Fracture2::Fracture2(0),
                                                   airwinconsolidated::Fracture2::kNumParameters,
                                                   rate, 0);
    if (key == "Gringer")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Gringer::Gringer(0),
                                                   airwinconsolidated::Gringer::kNumParameters,
                                                   rate, 0);
    if (key == "GuitarConditioner")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::GuitarConditioner::GuitarConditioner(0),
            airwinconsolidated::GuitarConditioner::kNumParameters, rate, 0);
    if (key == "PowerSag2")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::PowerSag2::PowerSag2(0),
                                                   airwinconsolidated::PowerSag2::kNumParameters,
                                                   rate, 0);
    if (key == "SingleEndedTriode")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::SingleEndedTriode::SingleEndedTriode(0),
            airwinconsolidated::SingleEndedTriode::kNumParameters, rate, 0);
    if (key == "Inflamer")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Inflamer::Inflamer(0),
                                                   airwinconsolidated::Inflamer::kNumParameters,
                                                   rate, 0);
    if (key == "Sweeten")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Sweeten::Sweeten(0),
                                                   airwinconsolidated::Sweeten::kNumParameters,
                                                   rate, 0);
    if (key == "BussColors4")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::BussColors4::BussColors4(0),
            airwinconsolidated::BussColors4::kNumParameters, rate, 0);
    if (key == "Channel9")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Channel9::Channel9(0),
                                                   airwinconsolidated::Channel9::kNumParameters,
                                                   rate, 0);
    if (key == "CStrip2")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::CStrip2::CStrip2(0),
                                                   airwinconsolidated::CStrip2::kNumParameters,
                                                   rate, 0);
    if (key == "Desk4")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Desk4::Desk4(0),
                                                   airwinconsolidated::Desk4::kNumParameters, rate,
                                                   0);
    if (key == "Discontapeity")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::Discontapeity::Discontapeity(0),
            airwinconsolidated::Discontapeity::kNumParameters, rate, 0);
    if (key == "Discontinuity")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::Discontinuity::Discontinuity(0),
            airwinconsolidated::Discontinuity::kNumParameters, rate, 0);
    if (key == "PurestWarm3")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::PurestWarm3::PurestWarm3(0),
            airwinconsolidated::PurestWarm3::kNumParameters, rate, 0);
    if (key == "Exciter")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Exciter::Exciter(0),
                                                   airwinconsolidated::Exciter::kNumParameters,
                                                   rate, 0);
    if (key == "Acceleration2")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::Acceleration2::Acceleration2(0),
            airwinconsolidated::Acceleration2::kNumParameters, rate, 0);
    if (key == "GoldenSlew")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::GoldenSlew::GoldenSlew(0),
            airwinconsolidated::GoldenSlew::kNumParameters, rate, 0);
    if (key == "Slew4")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Slew4::Slew4(0),
                                                   airwinconsolidated::Slew4::kNumParameters, rate,
                                                   0);
    if (key == "Smooth")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Smooth::Smooth(0),
                                                   airwinconsolidated::Smooth::kNumParameters, rate,
                                                   0);
    if (key == "Remap")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Remap::Remap(0),
                                                   airwinconsolidated::Remap::kNumParameters, rate,
                                                   0);
    if (key == "WoodenBox")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::WoodenBox::WoodenBox(0),
                                                   airwinconsolidated::WoodenBox::kNumParameters,
                                                   rate, 0);
    if (key == "BitGlitter")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::BitGlitter::BitGlitter(0),
            airwinconsolidated::BitGlitter::kNumParameters, rate, 0);
    if (key == "Bite")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Bite::Bite(0),
                                                   airwinconsolidated::Bite::kNumParameters, rate,
                                                   0);
    if (key == "ChromeOxide")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::ChromeOxide::ChromeOxide(0),
            airwinconsolidated::ChromeOxide::kNumParameters, rate, 0);
    if (key == "Cojones")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Cojones::Cojones(0),
                                                   airwinconsolidated::Cojones::kNumParameters,
                                                   rate, 0);
    if (key == "CrunchyGrooveWear")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::CrunchyGrooveWear::CrunchyGrooveWear(0),
            airwinconsolidated::CrunchyGrooveWear::kNumParameters, rate, 0);
    if (key == "DeBez")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::DeBez::DeBez(0),
                                                   airwinconsolidated::DeBez::kNumParameters, rate,
                                                   0);
    if (key == "DeRez3")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::DeRez3::DeRez3(0),
                                                   airwinconsolidated::DeRez3::kNumParameters, rate,
                                                   0);
    if (key == "Deckwrecka")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::Deckwrecka::Deckwrecka(0),
            airwinconsolidated::Deckwrecka::kNumParameters, rate, 0);
    if (key == "Dubly3")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Dubly3::Dubly3(0),
                                                   airwinconsolidated::Dubly3::kNumParameters, rate,
                                                   0);
    if (key == "Flutter2")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Flutter2::Flutter2(0),
                                                   airwinconsolidated::Flutter2::kNumParameters,
                                                   rate, 0);
    if (key == "GrooveWear")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::GrooveWear::GrooveWear(0),
            airwinconsolidated::GrooveWear::kNumParameters, rate, 0);
    if (key == "HipCrush")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::HipCrush::HipCrush(0),
                                                   airwinconsolidated::HipCrush::kNumParameters,
                                                   rate, 0);
    if (key == "Pockey2")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Pockey2::Pockey2(0),
                                                   airwinconsolidated::Pockey2::kNumParameters,
                                                   rate, 0);
    if (key == "TapeBias")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::TapeBias::TapeBias(0),
                                                   airwinconsolidated::TapeBias::kNumParameters,
                                                   rate, 0);
    if (key == "TapeDust")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::TapeDust::TapeDust(0),
                                                   airwinconsolidated::TapeDust::kNumParameters,
                                                   rate, 0);
    if (key == "Texturize")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Texturize::Texturize(0),
                                                   airwinconsolidated::Texturize::kNumParameters,
                                                   rate, 0);
    if (key == "ToVinyl4")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::ToVinyl4::ToVinyl4(0),
                                                   airwinconsolidated::ToVinyl4::kNumParameters,
                                                   rate, 0);
    if (key == "FromTape")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::FromTape::FromTape(0),
                                                   airwinconsolidated::FromTape::kNumParameters,
                                                   rate, 0);
    if (key == "IronOxideClassic2")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::IronOxideClassic2::IronOxideClassic2(0),
            airwinconsolidated::IronOxideClassic2::kNumParameters, rate, 0);
    if (key == "Tape")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Tape::Tape(0),
                                                   airwinconsolidated::Tape::kNumParameters, rate,
                                                   0);
    if (key == "ToTape8")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::ToTape8::ToTape8(0),
                                                   airwinconsolidated::ToTape8::kNumParameters,
                                                   rate, 1);
    if (key == "TapeHack2")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::TapeHack2::TapeHack2(0),
                                                   airwinconsolidated::TapeHack2::kNumParameters,
                                                   rate, 0);
    if (key == "Ensemble")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Ensemble::Ensemble(0),
                                                   airwinconsolidated::Ensemble::kNumParameters,
                                                   rate, 0);
    if (key == "GalacticVibe")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::GalacticVibe::GalacticVibe(0),
            airwinconsolidated::GalacticVibe::kNumParameters, rate, 0);
    if (key == "Melt")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Melt::Melt(0),
                                                   airwinconsolidated::Melt::kNumParameters, rate,
                                                   0);
    if (key == "TremoSquare")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::TremoSquare::TremoSquare(0),
            airwinconsolidated::TremoSquare::kNumParameters, rate, 0);
    if (key == "RingModulator")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::RingModulator::RingModulator(0),
            airwinconsolidated::RingModulator::kNumParameters, rate, 0);
    if (key == "GlitchShifter")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::GlitchShifter::GlitchShifter(0),
            airwinconsolidated::GlitchShifter::kNumParameters, rate, 0);
    if (key == "PitchNasty")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::PitchNasty::PitchNasty(0),
            airwinconsolidated::PitchNasty::kNumParameters, rate, 0);
    if (key == "StereoDoubler")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::StereoDoubler::StereoDoubler(0),
            airwinconsolidated::StereoDoubler::kNumParameters, rate, 0);
    if (key == "TripleSpread")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::TripleSpread::TripleSpread(0),
            airwinconsolidated::TripleSpread::kNumParameters, rate, 0);
    if (key == "FathomFive")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::FathomFive::FathomFive(0),
            airwinconsolidated::FathomFive::kNumParameters, rate, 0);
    if (key == "DubSub")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::DubSub::DubSub(0),
                                                   airwinconsolidated::DubSub::kNumParameters, rate,
                                                   0);
    if (key == "Srsly3")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Srsly3::Srsly3(0),
                                                   airwinconsolidated::Srsly3::kNumParameters, rate,
                                                   0);
    if (key == "StereoFX")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::StereoFX::StereoFX(0),
                                                   airwinconsolidated::StereoFX::kNumParameters,
                                                   rate, 0);
    if (key == "SweetWide")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::SweetWide::SweetWide(0),
                                                   airwinconsolidated::SweetWide::kNumParameters,
                                                   rate, 0);
    if (key == "Wider")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Wider::Wider(0),
                                                   airwinconsolidated::Wider::kNumParameters, rate,
                                                   0);
    if (key == "Sidepass")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Sidepass::Sidepass(0),
                                                   airwinconsolidated::Sidepass::kNumParameters,
                                                   rate, 0);
    if (key == "SideDull")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::SideDull::SideDull(0),
                                                   airwinconsolidated::SideDull::kNumParameters,
                                                   rate, 0);
    if (key == "ADT")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::ADT::ADT(0), airwinconsolidated::ADT::kNumParameters, rate, 0);
    if (key == "Hombre")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Hombre::Hombre(0),
                                                   airwinconsolidated::Hombre::kNumParameters, rate,
                                                   0);
    if (key == "StarChild2")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::StarChild2::StarChild2(0),
            airwinconsolidated::StarChild2::kNumParameters, rate, 0);
    if (key == "kChamberAR")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::kChamberAR::kChamberAR(0),
            airwinconsolidated::kChamberAR::kNumParameters, rate, 0);
    if (key == "BrightAmbience3")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::BrightAmbience3::BrightAmbience3(0),
            airwinconsolidated::BrightAmbience3::kNumParameters, rate, 0);
    if (key == "Chamber2")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Chamber2::Chamber2(0),
                                                   airwinconsolidated::Chamber2::kNumParameters,
                                                   rate, 0);
    if (key == "CrunchCoat")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::CrunchCoat::CrunchCoat(0),
            airwinconsolidated::CrunchCoat::kNumParameters, rate, 0);
    if (key == "Infinity2")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Infinity2::Infinity2(0),
                                                   airwinconsolidated::Infinity2::kNumParameters,
                                                   rate, 0);
    if (key == "MatrixVerb")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::MatrixVerb::MatrixVerb(0),
            airwinconsolidated::MatrixVerb::kNumParameters, rate, 0);
    if (key == "MV2")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::MV2::MV2(0), airwinconsolidated::MV2::kNumParameters, rate, 0);
    if (key == "NonlinearSpace")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::NonlinearSpace::NonlinearSpace(0),
            airwinconsolidated::NonlinearSpace::kNumParameters, rate, 0);
    if (key == "PocketVerbs")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::PocketVerbs::PocketVerbs(0),
            airwinconsolidated::PocketVerbs::kNumParameters, rate, 0);
    if (key == "Ultralight2")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::Ultralight2::Ultralight2(0),
            airwinconsolidated::Ultralight2::kNumParameters, rate, 0);
    if (key == "Verbity2")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::Verbity2::Verbity2(0),
                                                   airwinconsolidated::Verbity2::kNumParameters,
                                                   rate, 0);
    if (key == "kAlienSpaceship")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::kAlienSpaceship::kAlienSpaceship(0),
            airwinconsolidated::kAlienSpaceship::kNumParameters, rate, 0);
    if (key == "kCosmos")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::kCosmos::kCosmos(0),
                                                   airwinconsolidated::kCosmos::kNumParameters,
                                                   rate, 0);
    if (key == "kCyberCity")
        return std::make_unique<ImportedAirEffect>(
            new airwinconsolidated::kCyberCity::kCyberCity(0),
            airwinconsolidated::kCyberCity::kNumParameters, rate, 0);
    if (key == "kPlate140")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::kPlate140::kPlate140(0),
                                                   airwinconsolidated::kPlate140::kNumParameters,
                                                   rate, 0);
    if (key == "kPlate240")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::kPlate240::kPlate240(0),
                                                   airwinconsolidated::kPlate240::kNumParameters,
                                                   rate, 0);
    if (key == "kRockstar")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::kRockstar::kRockstar(0),
                                                   airwinconsolidated::kRockstar::kNumParameters,
                                                   rate, 0);
    if (key == "kStation")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::kStation::kStation(0),
                                                   airwinconsolidated::kStation::kNumParameters,
                                                   rate, 0);
    if (key == "kWoodRoom")
        return std::make_unique<ImportedAirEffect>(new airwinconsolidated::kWoodRoom::kWoodRoom(0),
                                                   airwinconsolidated::kWoodRoom::kNumParameters,
                                                   rate, 0);
    return {};
}
