import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { resolve } from 'node:path';
import { guideFor } from './effect-guides.mjs';
const root = fileURLToPath(new URL('../', import.meta.url));
const readJson = async (path) =>
  JSON.parse((await readFile(resolve(root, path), 'utf8')).replace(/^\uFEFF/, ''));
const native = await readJson('native/effects-catalogue.json');
const order = await readJson('effects/index.json');
const costs = await readJson('effects/dsp-costs.json');
const seen = new Set();
const data = [];
// Native DSP owns parameter ranges/order. Human-authored descriptors own presentation.
for (const file of order) {
  if (!/^[A-Za-z0-9-]+\.json$/.test(file)) throw new Error(`Invalid descriptor path: ${file}`);
  const descriptor = await readJson(`effects/${file}`);
  const key = descriptor.key.replace(/^fx-/, '');
  const engine = native.find((item) => item.key === key);
  if (!engine || seen.has(key)) throw new Error(`Missing or duplicate native effect: ${key}`);
  seen.add(key);
  if ('params' in descriptor || 'latency' in descriptor)
    throw new Error(`${file}: native fields must not be duplicated`);
  if (!descriptor.name || !descriptor.category)
    throw new Error(`${file}: name and category are required`);
  if (!descriptor.description?.trim())
    throw new Error(`${file}: a playing description is required`);
  const cost = costs.effects[descriptor.key];
  if (
    cost &&
    (!['Light', 'Moderate', 'Heavy'].includes(cost.tier) ||
      !Number.isFinite(cost.microseconds) ||
      cost.microseconds < 0)
  )
    throw new Error(`${file}: invalid DSP benchmark`);
  // Browser defaults are curated playable starting settings, not necessarily raw DSP defaults.
  const { defaults, ...presentation } = descriptor;
  if (!Array.isArray(defaults)) throw new Error(`${file}: defaults are required`);
  for (const preset of [{ name: 'Default', values: defaults }, ...(descriptor.presets ?? [])]) {
    if (preset.values.length !== engine.params.length)
      throw new Error(`${file}: wrong parameter count in ${preset.name}`);
    preset.values.forEach((value, index) => {
      const [, min, max] = engine.params[index];
      if (!Number.isFinite(value) || value < min - 0.00001 || value > max + 0.00001)
        throw new Error(`${file}: out-of-range preset ${preset.name}, parameter ${index}`);
    });
  }
  data.push({
    key: descriptor.key,
    latency: engine.latency,
    params: engine.params.map((parameter, index) =>
      parameter.map((value, field) => (field === 3 ? defaults[index] : value)),
    ),
    ...descriptor,
    ...(await guideFor(descriptor, engine)),
    dspCost: costs.effects[descriptor.key] ?? null,
  });
}
if (seen.size !== native.length)
  throw new Error('Every native effect needs exactly one descriptor.');
const outputs = {
  'prototype/effects-catalogue.js': `// GENERATED by scripts/build-effects.mjs. Edit effects/*.json instead.\n(function(root){const data=${JSON.stringify(data, null, 2)};if(typeof module==='object'&&module.exports)module.exports=data;else root.EffectsCatalogue=data;})(typeof window!=='undefined'?window:globalThis);\n`,
  'native/effect-presets.json':
    JSON.stringify(
      data.map((item) => ({ key: item.key.slice(3), presets: item.presets })),
      null,
      2,
    ) + '\n',
};
for (const [path, text] of Object.entries(outputs)) {
  if (process.argv.includes('--check')) {
    if ((await readFile(resolve(root, path), 'utf8')) !== text)
      throw new Error(`${path} is stale. Run npm run build.`);
  } else await writeFile(resolve(root, path), text);
}
