import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { resolve } from 'node:path';
const root = fileURLToPath(new URL('../', import.meta.url));
const manifest = JSON.parse(await readFile(resolve(root, 'src/legacy/manifest.json'), 'utf8'));
// Concatenate classic scripts without wrapping them: existing desktop integrations
// share their lexical scope. New UI features belong in ui/src React components.
for (const [group, output] of [
  ['app', 'app.js'],
  ['artwork', 'gear-looks.js'],
]) {
  const chunks = await Promise.all(
    manifest[group].map(
      async (path) => `// Source: ${path}\n${await readFile(resolve(root, path), 'utf8')}`,
    ),
  );
  const text =
    '// GENERATED by scripts/build-legacy.mjs. Edit src/legacy instead.\n' + chunks.join('\n');
  const target = resolve(root, 'prototype', output);
  if (process.argv.includes('--check')) {
    if ((await readFile(target, 'utf8')) !== text)
      throw new Error(`${output} is stale. Run npm run build.`);
  } else await writeFile(target, text);
}
