"""Embed CC0 cabinet recordings reproducibly; never normalise their gain.

Remove only leading silence below -80 dB relative to peak, retain 200 ms,
and apply a 10 ms cosine tail fade. Originals and handbooks remain in vendor.
Run before build-effects whenever the cabinet manifest/assets change.
"""
import sys
import json
import math
import wave
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BANK = ROOT / 'native/vendor/jester-cabs'
manifest = json.loads((BANK / 'cabinet-bank.json').read_text())
lines = ['// GENERATED by scripts/build-cabinet-data.py. Do not edit.',
         'struct CabinetRecording { const float *samples; int size; };']
for index, item in enumerate(manifest['recordings']):
    with wave.open(str(BANK / item['file'])) as wav:
        assert (wav.getframerate(), wav.getnchannels(), wav.getsampwidth()) == (48000, 1, 3)
        raw = wav.readframes(wav.getnframes())
    data = [int.from_bytes(raw[i:i+3], 'little', signed=True) / 8388608 for i in range(0, len(raw), 3)]
    threshold = max(map(abs, data)) * .0001
    start = next(i for i, x in enumerate(data) if abs(x) >= threshold)
    data = data[start:start + 9600]
    fade = min(480, len(data))
    for i in range(fade):
        data[len(data)-fade+i] *= .5 * (1 + math.cos(math.pi * i / (fade-1)))
    lines.append('static const float cabIR' + str(index) + '[] = {' + ','.join(format(x, '.9e') + 'f' for x in data) + '};')
lines.append('static const CabinetRecording cabinetRecordings[] = {' + ','.join('{cabIR%d, int(sizeof(cabIR%d)/sizeof(float))}' % (i,i) for i in range(len(manifest['recordings']))) + '};')
output = '\n'.join(lines) + '\n'
path = ROOT / 'native/cabinet-data.inc'
if '--check' in sys.argv:
    assert path.read_text() == output, 'Cabinet data is stale; run scripts/build-cabinet-data.py'
else:
    path.write_text(output)
