window.NativeDesktop=(()=>{
 const host=window.chrome?.webview;let drivers=[],running=false,timer;const send=value=>host?.postMessage(value);
 function sync(patch){if(!host)return;clearTimeout(timer);timer=setTimeout(()=>send({type:'sync',patch}),90);}
 let masterDb=-12;try{const saved=localStorage.getItem('guitar-suite-master-db');if(saved!==null&&Number.isFinite(Number(saved)))masterDb=Math.max(-30,Math.min(12,Number(saved)));}catch{}
 const dbLabel=value=>(value>0?'+':'')+value+' dB';
 let audioChoice={driver:'',input:0,output:0,rate:48000,inputName:'Input 1',outputName:'Outputs 1 + 2'};
 try{const saved=JSON.parse(localStorage.getItem('guitar-suite-audio-choice'));if(saved&&typeof saved.driver==='string'&&Number.isInteger(saved.input)&&saved.input>=0&&Number.isInteger(saved.output)&&saved.output>=0&&[44100,48000,96000].includes(saved.rate))audioChoice={...audioChoice,...saved};}catch{}
 function rememberAudio(){if(!$('#audio-driver'))return;audioChoice={driver:$('#audio-driver').value,input:Number($('#audio-input').value),output:Number($('#audio-output').value),rate:Number($('#audio-rate').value),inputName:$('#audio-input').selectedOptions[0]?.textContent||'Input',outputName:$('#audio-output').selectedOptions[0]?.textContent||'Output'};try{localStorage.setItem('guitar-suite-audio-choice',JSON.stringify(audioChoice));}catch{}}
 function restoreAudio(){const driver=$('#audio-driver');if(!driver)return;if(audioChoice.driver&&drivers.includes(audioChoice.driver))driver.value=audioChoice.driver;else if(audioChoice.driver){driver.add(new Option(audioChoice.driver+' (unavailable)',audioChoice.driver));driver.value=audioChoice.driver;$('#audio-message').textContent='Your saved driver is unavailable. Reconnect the interface or choose another driver.';}$('#audio-input').replaceChildren(new Option(audioChoice.inputName,audioChoice.input));$('#audio-output').replaceChildren(new Option(audioChoice.outputName,audioChoice.output));$('#audio-rate').value=String(audioChoice.rate);}
 function setup(){
  if(!host){modal('WINDOWS PROGRAM','<h2>Open Guitar Suite.exe to play.</h2><p>This browser tab is the design preview. The Windows program includes ASIO, built-in amps, NAM loading and cabinet IR import.</p>');return;}
  modal('WINDOWS AUDIO','<h2>Plug in and play.</h2><p>Choose your interface’s ASIO driver and guitar input. Raise Master output gradually if the patch is quiet. The output ceiling remains active. This first engine is mono, sent to both outputs.</p><label>Driver<select id="audio-driver">'+drivers.map(name=>'<option>'+escapeHTML(name)+'</option>').join('')+'</select></label><button id="inspect-driver">Read channels</button> <button id="driver-panel">Driver / buffer settings</button><div class="cable-form"><label>Guitar input<select id="audio-input"><option value="0">Input 1</option></select></label><label>Stereo output<select id="audio-output"><option value="0">Outputs 1 + 2</option></select></label><label>Sample rate<select id="audio-rate"><option value="48000">48,000 Hz</option><option value="44100">44,100 Hz</option><option value="96000">96,000 Hz</option></select></label></div><p id="audio-message" role="status">'+(running?'Audio is running.':'Audio is stopped. Use Read channels to see your interface inputs.')+'</p><label>Master output <strong id="master-label">'+dbLabel(masterDb)+'</strong><input id="master-output" type="range" min="-30" max="12" step="1" value="'+masterDb+'" aria-label="Master output in decibels"></label><p>0 dB removes the previous fixed reduction. This control changes volume, not amp drive.</p><label>Guitar input <span id="input-db">—</span></label><meter id="input-meter" min="0" max="1" value="0" aria-label="Guitar input level"></meter><label>App output <span id="output-db">—</span></label><meter id="output-meter" min="0" max="1" value="0" aria-label="App output level"></meter><p id="output-warning" role="status"></p><div class="transport"><button id="start-audio" class="primary">Start audio</button><button id="stop-audio">Stop audio</button></div><p>Adding or removing gear resumes audio on your chosen interface after a brief gap. Scenes and knobs work while playing. Tails/spillover and seamless routing changes are not implemented yet.</p>');restoreAudio();
 }
 function installed(){return !!host;}
 function importPatch(value){const candidate=PatchRig.migrate(value?.rig||value);if(!candidate){toast('This is not a supported Guitar Suite patch. A .nam model is imported on an amp.');return;}checkpoint();state=SlotBoard.assign(candidate);selected=state.blocks[0]?.id||null;render();toast('Patch imported. Import any missing NAM or IR files onto their devices.');}
 if(host)host.addEventListener('message',e=>{
  const message=e.data;
  if(message.type==='ready'){drivers=message.drivers;send({type:'master',db:masterDb});document.querySelector('.notice').innerHTML='<span class="tag">DESKTOP ALPHA</span> Built-in amps · ASIO · NAM + IR import · Audio starts only when you press Start.';catalogue.find(d=>d.key==='amp').detail='British crunch · Amplitron';catalogue.find(d=>d.key==='cleanamp').detail='American clean · Amplitron';catalogue.find(d=>d.key==='cab').detail='Filtered cabinet · IR ready';renderLibrary();render();}
  if(message.type==='status'){running=message.running;$('#settings').innerHTML=(running?'● ':'○ ')+escapeHTML(message.message)+' ↗';const line=$('#audio-message');if(line)line.textContent=message.message;document.querySelector('.statusbar').firstElementChild.textContent=message.message;document.querySelector('.statusbar').children[1].textContent=running?'ASIO active':'ASIO ready';document.querySelector('.chain-footer').firstElementChild.textContent=running?'Native audio engine running':'Native audio engine stopped';document.querySelector('.version').textContent='GUITAR SUITE / DESKTOP ALPHA';}
  if(message.type==='error'){toast(message.message);const line=$('#audio-message');if(line)line.textContent=message.message;}
  if(message.type==='meter'&&$('#input-meter')){const level=v=>v>0.00001?(20*Math.log10(v)).toFixed(1)+' dBFS':'—';$('#input-meter').value=Math.min(1,message.peak);$('#input-db').textContent=level(message.peak);$('#output-meter').value=message.output||0;$('#output-db').textContent=level(message.output);$('#output-warning').textContent=message.clipped?'Output reached its ceiling — lower Master output.':'';}
  if(message.type==='driver'&&$('#audio-input')){$('#audio-input').innerHTML=message.inputs.map((name,i)=>'<option value="'+i+'">'+escapeHTML(name)+'</option>').join('');$('#audio-output').innerHTML=message.outputs.slice(0,-1).map((name,i)=>'<option value="'+i+'">'+escapeHTML(name)+' + '+escapeHTML(message.outputs[i+1])+'</option>').join('');if(audioChoice.input<message.inputs.length)$('#audio-input').value=String(audioChoice.input);if(audioChoice.output<message.outputs.length-1)$('#audio-output').value=String(audioChoice.output);rememberAudio();}
  if(message.type==='asset'){const b=state.blocks.find(b=>b.id===message.blockId);if(!b)return;if(message.expectedKey&&(b.key!==message.expectedKey||(b.assetId||null)!==(message.expectedAsset||null))){toast('Device changed during download. The downloaded file stays in your local Library.');return;}checkpoint();b.assetId=message.assetId;b.assetName=message.assetName;if(message.tone){b.tone3000={...message.tone,modelId:message.modelId,architecture:message.architecture};$('#modal').close();}else delete b.tone3000;render();toast('Loaded '+message.assetName+'. Use '+message.rate.toLocaleString()+' Hz for playback.');}
  if(message.type==='patch')importPatch(message.value);
 });
 document.addEventListener('change',e=>{if(!['audio-driver','audio-input','audio-output','audio-rate'].includes(e.target.id))return;if(e.target.id==='audio-driver'){$('#audio-input').replaceChildren(new Option('Input 1',0));$('#audio-output').replaceChildren(new Option('Outputs 1 + 2',0));}rememberAudio();});
 document.addEventListener('input',e=>{if(e.target.id!=='master-output')return;masterDb=Number(e.target.value);$('#master-label').textContent=dbLabel(masterDb);send({type:'master',db:masterDb});try{localStorage.setItem('guitar-suite-master-db',String(masterDb));}catch{}});
 document.addEventListener('click',e=>{
  const button=e.target.closest('button');if(!button)return;
  if(button.id==='inspect-driver'||button.id==='driver-panel')send({type:'driver',driver:$('#audio-driver').value,panel:button.id==='driver-panel'});
  if(button.id==='start-audio'){rememberAudio();clearTimeout(timer);send({type:'sync',patch:state});send({type:'start',driver:$('#audio-driver').value,input:Number($('#audio-input').value),output:Number($('#audio-output').value),rate:Number($('#audio-rate').value)});}
  if(button.id==='stop-audio')send({type:'stop'});
  if(button.id==='import-model'){if(!host){setup();return;}const b=state.blocks.find(b=>b.id===selected);send({type:'importAsset',blockId:b.id,kind:b.key==='cab'?'cab':'amp'});}
  if(button.id==='factory-model'){const b=state.blocks.find(b=>b.id===selected);checkpoint();delete b.assetId;delete b.assetName;delete b.tone3000;render();}
  if(button.id==='import-patch'){if(host){send({type:'importPatch'});return;}const input=document.createElement('input');input.type='file';input.accept='.json';input.onchange=async()=>{try{if(input.files[0].size>4000000)throw Error();importPatch(JSON.parse(await input.files[0].text()));}catch{toast('Unable to read this patch file.');}};input.click();}
 });
 function controls(b){if(!['amp','cleanamp','cab'].includes(b.key))return '';return (window.ToneLibrary?ToneLibrary.controls(b):'')+'<div class="asset-tools"><span>'+escapeHTML(b.assetName||(b.key==='cab'?'Built-in filtered cabinet':'Built-in Amplitron amp'))+'</span><button id="import-model">Import '+(b.key==='cab'?'cab IR (.wav)':'NAM (.nam)')+'</button>'+(b.assetId?'<button id="factory-model">Use built-in</button>':'')+'</div>';}
 function boot(){if(host)send({type:'ready'});}
 function face(d,b,v){let html=HardwareControls.face(d,v);if(host&&!b.assetId)html=html.replace('NAM A2 / CAPTURE PLAYER','BUILT-IN / AMPLITRON').replace('TRIM & EQ CONTROLS SURROUND THE CAPTURE','AMP INPUT / TONE / OUTPUT').replace('CABINET IR / OUTPUT SHAPING','FILTERED CABINET / OUTPUT SHAPING');return html;}
 return {sync,setup,installed,controls,face,boot,exportPatch:value=>send({type:'exportPatch',value})};
})();
