// GENERATED by scripts/build-legacy.mjs. Edit src/legacy instead.
// Source: src/legacy/artwork/cabinets.js
// Cabinet geometry shared by compact and expanded device views.
/* Cabinet geometry is shared by the editor and thumbnails. Dimensions are
   representative enclosure proportions, not claims about a particular IR. */
const CabinetLooks = (() => {
  const formats = [
    ['1x10', '1 × 10 · compact', 42, 38, 10, 1, 1],
    ['1x12', '1 × 12 · standard', 52, 45, 12, 1, 1],
    ['1x15', '1 × 15 · bass', 61, 63, 15, 1, 1],
    ['2x10', '2 × 10 · horizontal', 61, 40, 10, 2, 1],
    ['2x12', '2 × 12 · horizontal', 76, 49, 12, 2, 1],
    ['2x12v', '2 × 12 · vertical', 49, 76, 12, 1, 2],
    ['4x10', '4 × 10 · compact quad', 60, 62, 10, 2, 2],
    ['4x12', '4 × 12 · straight', 77, 83, 12, 2, 2],
    ['4x12s', '4 × 12 · slant', 77, 83, 12, 2, 2],
    ['8x10', '8 × 10 · bass tower', 66, 123, 10, 2, 4],
  ];
  const esc = (s) =>
    String(s).replace(
      /[&<>"']/g,
      (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c],
    );
  function get(b, d) {
    if (b.key.startsWith('fx-CabJester') && !b.appearance?.cabFormat)
      return formats.find((f) => f[0] === '4x12');
    const explicit = formats.find((f) => f[0] === b.appearance?.cabFormat);
    if (explicit) return explicit;
    const name = ((b.tone3000?.title || '') + ' ' + (b.assetName || ''))
      .toLowerCase()
      .replace(/\s/g, '')
      .replace(/×/g, 'x');
    return (
      [...formats].sort((a, b) => b[0].length - a[0].length).find((f) => name.includes(f[0])) ||
      formats.find((f) => f[0] === d.speakers + 'x12') ||
      formats[4]
    );
  }
  function selector(b, d) {
    return (
      '<label>Cabinet format<select id="cabinet-format" aria-label="Cabinet format">' +
      formats
        .map(
          (f) =>
            '<option value="' +
            f[0] +
            '" ' +
            (get(b, d)[0] === f[0] ? 'selected' : '') +
            '>' +
            f[1] +
            '</option>',
        )
        .join('') +
      '</select></label>'
    );
  }
  function svg(b, d) {
    const f = get(b, d),
      [key, label, w, h, size, cols, rows] = f,
      body = /^#[a-f0-9]{6}$/i.test(b.appearance?.colour || '') ? b.appearance.colour : d.body;
    const border = 4,
      top = 8,
      bottom = 5,
      gw = w - border * 2,
      gh = h - top - bottom,
      r = ((size * 2.54) / 2) * 0.86;
    let speakers = '';
    for (let row = 0; row < rows; row++)
      for (let col = 0; col < cols; col++) {
        const x = border + (gw * (col + 0.5)) / cols,
          y = top + (gh * (row + 0.5)) / rows;
        speakers += `<g transform="translate(${x} ${y})"><circle r="${r}" fill="#0b0d0e" stroke="#5e6260" stroke-width=".55"/><circle r="${r * 0.88}" fill="url(#cone)"/>${[0.38, 0.49, 0.6, 0.7, 0.8].map((v) => `<circle r="${r * v}" fill="none" stroke="#777" stroke-opacity=".17" stroke-width=".22"/>`).join('')}<circle r="${r * 0.27}" fill="#131516" stroke="#333738" stroke-width=".4"/></g>`;
      }
    return `<svg xmlns="http://www.w3.org/2000/svg" class="gear-svg cabinet-art" viewBox="-3 -3 ${w + 6} ${h + 10}" role="img" aria-label="${esc(label)} cabinet"><defs><linearGradient id="case" x2="1" y2="1"><stop stop-color="${body}"/><stop offset="1" stop-color="#111"/></linearGradient><radialGradient id="cone"><stop stop-color="#262a2b"/><stop offset=".5" stop-color="#454b4d"/><stop offset=".82" stop-color="#292e30"/><stop offset="1" stop-color="#080b0c"/></radialGradient><pattern id="grain" width="1.7" height="1.3" patternUnits="userSpaceOnUse"><path d="M0 .3L1 .6 .5 1.3" stroke="#fff" stroke-opacity=".13" stroke-width=".2"/></pattern><pattern id="cloth" width="1.05" height="1.05" patternUnits="userSpaceOnUse"><path d="M0 .2h1.05M.2 0v1.05" stroke="${d.grille}" stroke-width=".28"/><path d="M0 .7h1.05M.7 0v1.05" stroke="#aaa38d" stroke-opacity=".35" stroke-width=".16"/></pattern></defs><ellipse cx="${w / 2}" cy="${h + 3}" rx="${w * 0.48}" ry="2" fill="#000" opacity=".4"/><rect x="6" y="${h - 1}" width="8" height="4" rx="1" fill="#131616"/><rect x="${w - 14}" y="${h - 1}" width="8" height="4" rx="1" fill="#131616"/><rect width="${w}" height="${h}" rx="2.3" fill="url(#case)" stroke="#656764" stroke-width=".5"/><rect width="${w}" height="${h}" rx="2.3" fill="url(#grain)"/><rect x="${border - 1}" y="${top - 1}" width="${gw + 2}" height="${gh + 2}" rx=".8" fill="${d.panel}"/><rect x="${border}" y="${top}" width="${gw}" height="${gh}" fill="#141819"/>${speakers}<rect x="${border}" y="${top}" width="${gw}" height="${gh}" fill="url(#cloth)" opacity=".83"/>${key === '4x12s' ? `<path d="M4 ${h * 0.46}H${w - 4}L${w - 5} 8H5Z" fill="#fff" opacity=".065"/><path d="M4 ${h * 0.46}H${w - 4}" stroke="#070909" stroke-opacity=".5" stroke-width=".7"/>` : ''}<rect x="${w * 0.3}" y="2" width="${w * 0.4}" height="3" rx="1" fill="#0e1111" stroke="#707571" stroke-width=".3"/>${[
      [0, 0],
      [w - 6, 0],
      [0, h - 6],
      [w - 6, h - 6],
    ]
      .map(
        ([x, y]) =>
          `<rect x="${x}" y="${y}" width="6" height="6" rx="1" fill="#202424" stroke="#686c68" stroke-width=".3"/><circle cx="${x + 3}" cy="${y + 3}" r=".6" fill="#b0b5ad"/>`,
      )
      .join(
        '',
      )}<rect x="${w * 0.32}" y="${top + 1.5}" width="${w * 0.36}" height="5" rx=".4" fill="#181c1d" stroke="${d.panel}" stroke-width=".3"/><text x="${w / 2}" y="${top + 5}" text-anchor="middle" fill="#e4dcc6" font-family="Arial,sans-serif" font-size="2.7" letter-spacing=".5">${cols * rows} × ${size}</text></svg>`;
  }
  function image(b, d, large = false) {
    const f = get(b, d);
    return (
      '<img class="gear-svg cabinet-art' +
      (large ? ' cabinet-large' : '') +
      '" src="data:image/svg+xml,' +
      encodeURIComponent(svg(b, d)) +
      '" alt="' +
      esc(f[1]) +
      ' cabinet"' +
      (large
        ? ' style="--cab-width:' +
          f[2] +
          ';width:min(100%,calc(var(--cab-width)*var(--cab-scale,6px)))"'
        : '') +
      '>'
    );
  }
  function skin(b, d, html) {
    const controls = html.match(
      /<div class="cabinet-panel">([\s\S]*?)<\/div><div class="hardware-caption">/,
    );
    return (
      '<div class="hardware-stage cabinet-stage"><div class="cabinet-product">' +
      image(b, d, true) +
      '<span class="cabinet-format-caption">' +
      esc(get(b, d)[1]) +
      '</span></div><div class="hardware-face cabinet-adjustments"><span class="cabinet-controls-title">CABINET / OUTPUT SHAPING</span>' +
      (controls?.[1] || '') +
      '</div></div>'
    );
  }
  return { get, selector, image, skin, formats };
})();

/* Original hardware-inspired illustrations; appearance never selects a DSP model. */

// Source: src/legacy/artwork/hardware.js
// Hardware appearance and controls; cabinet geometry lives in cabinets.js.
window.GearLooks = (() => {
  const esc = (s) =>
    String(s ?? '').replace(
      /[&<>"']/g,
      (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c],
    );
  const designs = [
    ['British Gold', '#292826', '#c7a866', '#393632', 'gold', 2],
    ['American Blackface', '#202326', '#bfc2bf', '#70777a', 'silver', 2],
    ['Golden Tweed', '#bc9958', '#876c41', '#665442', 'tweed', 1],
    ['Orange Box', '#cd672e', '#e8d7a4', '#826b48', 'cream', 2],
    ['Diamond Boutique', '#472e24', '#a57b43', '#816948', 'diamond', 2],
    ['California Rectifier', '#1e2022', '#909599', '#25282c', 'steel', 4],
    ['German Steel', '#202227', '#afb2ac', '#52575b', 'steel', 4],
    ['Ivory Boutique', '#d4c9a8', '#725e40', '#948268', 'cream', 1],
    ['Brown Panel', '#614833', '#a58759', '#756754', 'tweed', 2],
    ['Silver Sparkle', '#777f83', '#d5d8d5', '#393f43', 'silver', 2],
    ['Red High Gain', '#8b2928', '#161a1e', '#333337', 'steel', 4],
    ['Blue Chime', '#274f69', '#d5c797', '#7c7a6a', 'diamond', 2],
    ['Olive Vintage', '#5e6741', '#baac75', '#443f2e', 'gold', 1],
    ['Purple Stack', '#654568', '#c3a379', '#29282c', 'gold', 4],
    ['Walnut Studio', '#6d4a30', '#d8c3a1', '#8e7b61', 'wood', 1],
    ['Blackout Modern', '#151718', '#4a5051', '#171c1f', 'steel', 4],
    ['Seafoam Combo', '#85a89b', '#ded3b4', '#817c6a', 'silver', 2],
    ['Red Tolex', '#9e3e37', '#d8c49b', '#55483d', 'cream', 2],
    ['Copper Boutique', '#4a3932', '#b68861', '#57504a', 'gold', 1],
    ['White Stadium', '#d2d0c7', '#3d4246', '#474e51', 'steel', 4],
  ];
  const families = [
    ['Marshall', 'head', 'gold', 'script'],
    ['Fender blackface', 'combo', 'black', 'script'],
    ['Fender tweed', 'combo', 'tweed', 'script'],
    ['Orange', 'head', 'cream', 'block'],
    ['VOX', 'combo', 'diamond', 'serif'],
    ['Mesa/Boogie', 'head', 'steel', 'plate'],
    ['ENGL', 'head', 'steel', 'block'],
    ['Matchless', 'combo', 'cream', 'plate'],
    ['Fender brownface', 'combo', 'brown', 'script'],
    ['Fender silverface', 'combo', 'silver', 'script'],
    ['Soldano', 'head', 'black', 'block'],
    ['VOX', 'combo', 'diamond', 'serif'],
    ['Hiwatt', 'head', 'black', 'plate'],
    ['Bogner', 'head', 'gold', 'script'],
    ['Boutique wood', 'combo', 'wood', 'serif'],
    ['Diezel', 'head', 'steel', 'block'],
    ['Fender custom', 'combo', 'silver', 'script'],
    ['Orange custom', 'head', 'cream', 'block'],
    ['Friedman', 'head', 'gold', 'script'],
    ['Peavey', 'head', 'black', 'block'],
  ];
  const pedalNames = [
    'Compact cast',
    'Compact treadle',
    'Folded steel',
    'Wide studio',
    'Green overdrive',
    'Black distortion',
    'Silver fuzz',
    'Cream boost',
    'Brown drive',
    'Silver modulation',
    'Red distortion',
    'Blue chorus',
    'Olive drive',
    'Purple modulation',
    'Copper tremolo',
    'Black studio',
    'Seafoam delay',
    'Red fuzz',
    'Copper boost',
    'White ambience',
  ];
  const pedalBrands = [
    'MXR',
    'BOSS',
    'Electro-Harmonix',
    'Strymon',
    'Ibanez',
    'Pro Co',
    'Dunlop',
    'boutique',
    'boutique',
    'Electro-Harmonix',
    'BOSS',
    'BOSS',
    'MXR',
    'boutique',
    'boutique',
    'Eventide',
    'TC Electronic',
    'Dunlop',
    'boutique',
    'Strymon',
  ];
  const kind = (b) =>
    PatchRig.definition(b.key)?.type === 'Cabs'
      ? 'cab'
      : PatchRig.definition(b.key)?.type === 'Amps'
        ? 'amp'
        : 'pedal';
  function list(b) {
    const pedal = kind(b) === 'pedal';
    return designs.map((d, i) => ({
      id: 'look-' + i,
      name: pedal ? pedalNames[i] : d[0],
      body: d[1],
      panel: d[2],
      grille: d[3],
      texture: d[4],
      speakers: d[5],
      brand: pedal ? pedalBrands[i] : families[i][0],
      format: families[i][1],
      face: pedal
        ? [1, 10, 11].includes(i)
          ? 'pedal-treadle'
          : [3, 15, 19].includes(i)
            ? 'pedal-wide'
            : [2, 6, 9].includes(i)
              ? 'pedal-folded'
              : 'pedal-cast'
        : families[i][2],
      badge: families[i][3],
    }));
  }

  function get(b) {
    const all = list(b);
    return (
      all.find((d) => d.id === b.appearance?.style) ||
      all.find((d) => d.id === PatchRig.definition(b.key)?.defaultLook) ||
      all[
        b.appearance?.style === 'tweed'
          ? 2
          : b.appearance?.style === 'modern'
            ? 5
            : b.key === 'cleanamp' || b.key === 'fx-GXOrange'
              ? 1
              : b.key === 'drive'
                ? 4
                : 0
      ]
    );
  }
  function selector(b) {
    const selected = get(b);
    return (
      (kind(b) === 'cab' ? CabinetLooks.selector(b, selected) : '') +
      '<label>Hardware look<select id="device-look" aria-label="Hardware look">' +
      list(b)
        .map(
          (d) =>
            '<option value="' +
            d.id +
            '" ' +
            (d.id === selected.id ? 'selected' : '') +
            '>' +
            esc(d.name + ' · ' + d.brand + '-style') +
            '</option>',
        )
        .join('') +
      '</select></label>'
    );
  }
  let seq = 0;
  function art(b, on = true) {
    if (kind(b) === 'cab') return CabinetLooks.image(b, get(b));
    if (kind(b) === 'pedal' && !b.appearance) return GearArt.svg(b.key, on);
    const d = get(b),
      id = 'look' + ++seq,
      body = /^#[a-f0-9]{6}$/i.test(b.appearance?.colour || '') ? b.appearance.colour : d.body,
      type = kind(b),
      four = d.speakers === 4,
      cab = type === 'cab',
      pedal = type === 'pedal';
    const x = pedal ? 49 : cab && d.speakers === 1 ? 43 : 13,
      w = pedal ? 102 : cab && d.speakers === 1 ? 114 : 174,
      y = cab ? 10 : pedal ? 8 : 28,
      h = cab ? 137 : pedal ? 138 : 108;
    let inside = '';
    if (cab) {
      const coords =
        d.speakers === 1
          ? [[100, 81, 42]]
          : four
            ? [
                [61, 54, 29],
                [139, 54, 29],
                [61, 115, 29],
                [139, 115, 29],
              ]
            : [
                [59, 88, 36],
                [140, 88, 36],
              ];
      inside =
        coords
          .map(
            ([a, c, r]) =>
              '<circle cx="' +
              a +
              '" cy="' +
              c +
              '" r="' +
              r +
              '" fill="url(#' +
              id +
              'cone)" stroke="#9996"/><circle cx="' +
              a +
              '" cy="' +
              c +
              '" r="' +
              r * 0.24 +
              '" fill="#1c2021"/>',
          )
          .join('') +
        '<rect x="' +
        (x + 9) +
        '" y="21" width="' +
        (w - 18) +
        '" height="115" fill="url(#' +
        id +
        'weave)"/><rect x="72" y="25" width="56" height="15" fill="' +
        d.panel +
        '"/><text x="100" y="35" text-anchor="middle" font-size="7" fill="#171a18">' +
        d.speakers +
        ' × 12</text>';
    } else if (pedal) {
      inside =
        [73, 101, 129]
          .map(
            (a) =>
              '<circle cx="' +
              a +
              '" cy="33" r="9" fill="#242726" stroke="#c4c9b5"/><path d="M' +
              a +
              ' 25v6" stroke="#fff"/>',
          )
          .join('') +
        '<text x="100" y="70" fill="#f0e9d9" text-anchor="middle" font-size="10">' +
        esc(PatchRig.definition(b.key)?.name?.slice(0, 18) || 'CAPTURE') +
        '</text><path d="M72 91q14-24 28 0t28 0" stroke="#fff7" fill="none"/><circle cx="100" cy="122" r="11" fill="#bbc0b7" stroke="#454944"/><circle cx="125" cy="111" r="3" fill="' +
        (on ? '#e5ffa9' : '#464b43') +
        '"/>';
    } else {
      const combo = d.format === 'combo',
        grilleY = combo ? 76 : 40,
        panelY = combo ? 40 : 98;
      inside =
        '<rect x="23" y="' +
        grilleY +
        '" width="154" height="' +
        (combo ? 47 : 52) +
        '" fill="url(#' +
        id +
        'weave)"/><text x="100" y="' +
        (grilleY + 32) +
        '" text-anchor="middle" fill="#f1e4c9" font-family="' +
        (d.badge === 'script' ? 'Georgia' : 'Arial') +
        '" font-style="' +
        (d.badge === 'script' ? 'italic' : 'normal') +
        '" font-size="17">' +
        esc(d.name.split(' ')[0]) +
        '</text><rect x="23" y="' +
        panelY +
        '" width="154" height="' +
        (combo ? 31 : 25) +
        '" rx="2" fill="' +
        (d.face === 'black' || d.face === 'steel' ? '#161a1b' : d.panel) +
        '"/>' +
        [37, 57, 77, 97, 117, 137]
          .map(
            (a) =>
              '<circle cx="' +
              a +
              '" cy="' +
              (panelY + 13) +
              '" r="5" fill="#282b28" stroke="#bbb8a7"/><path d="M' +
              a +
              ' ' +
              (panelY + 8) +
              'v3" stroke="#fff"/>',
          )
          .join('') +
        '<circle cx="165" cy="' +
        (panelY + 13) +
        '" r="3" fill="' +
        (on ? '#ffaa63' : '#4b4134') +
        '"/>';
    }

    return (
      '<svg class="gear-svg" viewBox="0 0 200 160" aria-hidden="true"><defs><pattern id="' +
      id +
      'tolex" width="200" height="160" patternUnits="userSpaceOnUse"><image href="tolex-black.png" width="200" height="160"/></pattern><radialGradient id="' +
      id +
      'cone"><stop stop-color="#15191a"/><stop offset=".4" stop-color="#43494a"/><stop offset=".85" stop-color="#22292a"/><stop offset="1" stop-color="#5c625e"/></radialGradient><pattern id="' +
      id +
      'weave" width="' +
      (d.texture === 'diamond' ? 12 : 4) +
      '" height="' +
      (d.texture === 'diamond' ? 12 : 4) +
      '" patternUnits="userSpaceOnUse"><rect width="20" height="20" fill="' +
      d.grille +
      '" opacity=".55"/><path d="' +
      (d.texture === 'diamond' ? 'M0 6L6 0l6 6-6 6Z' : 'M0 0h4v4') +
      '" stroke="#ddd8" stroke-width=".5" fill="none"/></pattern><linearGradient id="' +
      id +
      'shine" x2=".7" y2="1"><stop stop-color="#ffffff22"/><stop offset="1" stop-color="#0005"/></linearGradient></defs><ellipse cx="100" cy="151" rx="80" ry="6" fill="#0005"/>' +
      (!pedal && !cab
        ? '<path d="M74 28v-9h52v9" stroke="#7a7c71" stroke-width="6" fill="none"/>'
        : '') +
      '<rect x="' +
      x +
      '" y="' +
      y +
      '" width="' +
      w +
      '" height="' +
      h +
      '" rx="' +
      (d.texture === 'steel' ? 3 : 8) +
      '" fill="' +
      body +
      '" stroke="#161b1a" stroke-width="4"/><rect x="' +
      x +
      '" y="' +
      y +
      '" width="' +
      w +
      '" height="' +
      h +
      '" rx="6" fill="url(#' +
      id +
      'tolex)" opacity=".35"/><rect x="' +
      (x + 6) +
      '" y="' +
      (y + 6) +
      '" width="' +
      (w - 12) +
      '" height="' +
      (h - 12) +
      '" fill="url(#' +
      id +
      'shine)"/>' +
      inside +
      '</svg>'
    );
  }
  function skin(b, html) {
    const d = get(b);
    if (kind(b) === 'cab') return CabinetLooks.skin(b, d, html);
    const body = /^#[a-f0-9]{6}$/i.test(b.appearance?.colour || '') ? b.appearance.colour : d.body;
    const paint =
      kind(b) === 'pedal' && !b.appearance ? PatchRig.definition(b.key)?.colour || body : body;
    const rgb = /^#[a-f0-9]{6}$/i.test(paint)
      ? [1, 3, 5].map((i) => parseInt(paint.slice(i, i + 2), 16))
      : [50, 50, 50];
    const ink = rgb[0] * 0.299 + rgb[1] * 0.587 + rgb[2] * 0.114 > 145 ? '#182522' : '#f2efe1';
    if (kind(b) === 'cab')
      html = html.replace('<i></i><i></i><strong>', '<i></i>'.repeat(d.speakers) + '<strong>');
    return (
      '<div class="custom-device ' +
      (/^#[a-f0-9]{6}$/i.test(b.appearance?.colour || '') ? 'colour-custom ' : '') +
      'look-' +
      d.texture +
      ' speakers-' +
      d.speakers +
      ' family-' +
      d.face +
      ' format-' +
      d.format +
      ' badge-' +
      d.badge +
      ' device-' +
      kind(b) +
      '" style="--device-colour:' +
      (kind(b) === 'pedal' && !b.appearance ? PatchRig.definition(b.key)?.colour || body : body) +
      ';--pedal-ink:' +
      ink +
      ';--look-panel:' +
      d.panel +
      ';--look-grille:' +
      d.grille +
      '">' +
      html +
      '<div class="hardware-style-credit">' +
      esc(d.brand + '-style enclosure') +
      ' · appearance only</div></div>'
    );
  }
  return { list, get, selector, art, skin };
})();
