const fs=require('fs');
const catalogue=JSON.parse(fs.readFileSync('native/effects-catalogue.json','utf8').replace(/^\uFEFF/,''));
for(const d of catalogue)for(const p of d.params)for(let i=1;i<=3;i++)p[i]=Number(p[i].toFixed(4));
const names={ShimmerHall:'Shimmer Hall',GXOrange:'Orange Distortion',GXPlus:'Distortion Plus',GXFuzz:'Round Fuzz',GXMuff:'Sustain Fuzz',GXScream:'Scream Drive',GXSoft:'Soft Clip',SurgeFloaty:'Warp Echo',SurgeReverb:'Modulated Space',Spring:'Spring Tank',DiffuseDelay:'Diffuse Echo',SurgeDelay:'Stereo Digital',TapeDelay2:'Tape Machine',Doublelay:'Double Echo',PitchDelay:'Pitch Echo',PurestEcho:'Four Tap',DragonHall:'Dragon Hall',DragonRoom:'Dragon Room',DragonPlate:'Dragon Plate',Galactic3:'Galactic',CreamCoat:'Cream Plate',kCathedral5:'Cathedral',kGuitarHall2:'Guitar Hall',StereoChorus:'Stereo Chorus',StereoEnsemble:'Ensemble',SurgeFlanger:'Jet Flanger',SurgePhaser:'Phase Sweep',SurgeRotary:'Rotary Speaker',Vibrato:'Pitch Vibrato',Tremolo:'Tremolo',AutoPan:'Auto Pan'};
const defaults={TapeDelay2:[40,30,50,0,12,25],Doublelay:[20,20,30,25,30],PitchDelay:[40,25,50,0,58,25],PurestEcho:[35,30,20,12,8],Galactic3:[50,50,35,100,80,30],kCathedral5:[50,60,24,50,50,25],kGuitarHall2:[45,60,50,50,50,25],StereoChorus:[30,40],StereoEnsemble:[45,55],Vibrato:[30,25,40,0,100],Tremolo:[45,50],AutoPan:[25,50,60,70]};
const all=catalogue.map(d=>{const drive=d.key.startsWith('GX'),delay=/Delay|lay|Echo|Floaty/.test(d.key),verb=/Dragon|Galactic|Cream|Cathedral|GuitarHall|Spring|Reverb|Shimmer/.test(d.key),category=drive?'Drive':delay?'Delay':verb?'Reverb':'Modulation';const engine=d.key==='ShimmerHall'?'Signalsmith / Dragonfly':drive?'Guitarix':d.key==='Spring'?'Surge / ChowDSP':d.key==='DiffuseDelay'?'ChowMatrix diffusion adaptation':d.key.startsWith('Dragon')?'Dragonfly':d.key.startsWith('Surge')?'Surge':'Airwindows';let values=defaults[d.key]||d.params.map(p=>p[3]);d.params.forEach((p,i)=>p[3]=Number(values[i].toFixed(3)));values=d.params.map(p=>p[3]);const alt=[...values];const mix=d.params.findIndex(p=>/Mix|Wet/.test(p[0]));if(d.key==='SurgeDelay'){alt[1]=570;alt[3]=35;}if(mix>=0)alt[mix]=Math.min(d.params[mix][2],values[mix]*1.6);const fb=d.params.findIndex(p=>/Feedback|Regen|Decay/.test(p[0]));if(fb>=0)alt[fb]=Math.min(d.params[fb][2]*.8,values[fb]*1.35);if(mix<0&&fb<0)alt[0]=Math.min(d.params[0][2],values[0]*1.5);return {...d,key:'fx-'+d.key,name:names[d.key],type:'Pedals',category,engine,detail:category+' · '+engine,icon:drive?'↯':delay?'≈':verb?'✧':'∿',colour:drive?'#be8b55':delay?'#69afb5':verb?'#b597cb':'#83b99b',sync:['SurgeDelay','DiffuseDelay'].includes(d.key),presets:[{name:'Balanced',values},{name:drive?'Pushed':delay?'Wide repeats':verb?'Deep space':'Deep movement',values:alt}]};});
for(const d of all){
 if(d.key==='fx-SurgeFloaty'){const reverse=[...d.presets[0].values];reverse[1]=-1;reverse[2]=40;reverse[10]=45;d.presets.push({name:'Reverse wash',values:reverse});}
 if(d.key==='fx-ShimmerHall'){d.presets[0].name='Octave sky';d.presets[1]={name:'Fifth cloud',values:[8,65,5500,42,7]};d.presets.push({name:'Low octave haze',values:[5,50,4500,30,-12]});}
 if(d.key==='fx-SurgeReverb'){const cloud=[...d.presets[0].values];cloud[1]=20;cloud[2]=8;cloud[9]=45;d.presets.push({name:'Long cloud',values:cloud});}
}
fs.writeFileSync('native/effect-presets.json',JSON.stringify(all.map(d=>({key:d.key.slice(3),presets:d.presets})),null,2));
fs.writeFileSync((fs.existsSync('prototype')?'prototype/':'')+'effects-catalogue.js',`/* Generated from the compiled native parameter catalogue. */\n(function(root){const data=${JSON.stringify(all,null,2)};if(typeof module==='object'&&module.exports)module.exports=data;else root.EffectsCatalogue=data;})(globalThis);\n`);
