window.PatchUI=(()=>{
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let scale=1;
  function name(s,id){const b=s.blocks.find(b=>b.id===id);return b?`${PatchRig.definition(b.key).name} ${s.blocks.indexOf(b)+1}`:({input:'Guitar input',output:'Stereo output',split:'Saved splitter',merge:'Saved mixer','path-a':'Saved trim'}[id]||id);}
  function nodes(s){return [{id:'input',x:30,y:100,terminal:true},...s.blocks,...s.junctions,{id:'output',...s.output,terminal:true}];}
  function port(s,b,side,pending){return `<button class="cable-port ${side} ${pending===b.id&&side==='out'?'pending':''}" data-port="${side}" data-node="${b.id}" aria-label="${side==='out'?'Connect from':'Connect to'} ${esc(name(s,b.id))}" title="${side==='out'?'Output: click, then click an input':'Input: accepts multiple cables'}">${side==='out'?'›':'‹'}</button>`;}
  function render(s,selected,pending=null){
    const list=nodes(s),width=Math.max(1150,...list.map(b=>b.x+180)),height=Math.max(480,...list.map(b=>b.y+200)),active=PatchRig.activeNodes(s),unconnected=s.blocks.filter(b=>!active.has(b.id));
    document.querySelector('#routing-bar').innerHTML=`<div class="patch-tools"><span class="graph-badge">FREE ROUTING</span><button id="wire-list">Cables · ${s.connections.length}</button><button id="arrange">Tidy board</button><button id="routing-example">Pre-amp delay example</button><label>Zoom <select id="board-zoom" aria-label="Board zoom"><option value="fit">Fit board</option><option value="1">100%</option><option value="0.8">80%</option></select></label></div>`;
    const zoom=document.querySelector('#chain').dataset.zoom||'fit';document.querySelector('#board-zoom').value=zoom;
    scale=zoom==='fit'?Math.max(.4,Math.min(1,(document.querySelector('#chain').clientWidth-16)/width)):Number(zoom);
    document.querySelector('#routing-summary').textContent=unconnected.length?`${unconnected.length} device(s) outside the input → output route`:'Input → output connected';
    document.querySelector('#chain').innerHTML=`<div class="patch-scroll-size" style="width:${width*scale}px;height:${height*scale}px"><div class="patch-board" style="width:${width}px;height:${height}px;transform:scale(${scale})"><svg class="patch-wires" width="${width}" height="${height}" aria-hidden="true"><defs><marker id="flow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#bdcf80"/></marker></defs>${s.connections.map(([a,b],i)=>{const from=list.find(n=>n.id===a),to=list.find(n=>n.id===b),x1=from.x+130,y1=from.y+78,x2=to.x,y2=to.y+78,curve=Math.max(35,Math.abs(x2-x1)*.48),d=`M${x1},${y1} C${x1+curve},${y1} ${x2-curve},${y2} ${x2},${y2}`;return `<path class="cable ${selected===a||selected===b?'lit':''}" d="${d}" marker-end="url(#flow)"/><path class="cable-hit" data-cable="${i}" d="${d}"><title>${esc(name(s,a)+' → '+name(s,b))}</title></path>`;}).join('')}</svg>${list.map(b=>{
      const d=b.key&&PatchRig.definition(b.key),on=d&&s.scenes[s.scene][b.id].on;
      return `<div class="patch-node ${d?'device-node':'terminal-node'} ${selected===b.id?'selected':''} ${d&&!active.has(b.id)?'unconnected':''}" style="left:${b.x}px;top:${b.y}px;--accent:${d?.colour||'#bdcf80'}">${b.id!=='input'?port(s,b,'in',pending):''}${d?`<button class="patch-gear ${on?'':'bypassed'}" data-block="${b.id}" aria-label="Edit ${esc(name(s,b.id))}" aria-pressed="${selected===b.id}">${GearArt.svg(b.key,on)}<strong>${esc(d.name)}</strong><small>${s.blocks.indexOf(b)+1} / ${on?'ON':'BYPASSED'}</small></button><button class="node-bypass" data-node-bypass="${b.id}" aria-label="${on?'Bypass':'Enable'} ${esc(name(s,b.id))}">${on?'●':'○'}</button>`:`<button class="patch-terminal" ${b.terminal?'disabled':`data-legacy="${b.id}"`}><span>${b.id==='input'?'◎':b.id==='output'?'◉':b.id==='split'?'⑂':'⋈'}</span>${esc(name(s,b.id))}</button>`}${b.id!=='output'?port(s,b,'out',pending):''}</div>`;
    }).join('')}</div></div>`;
    document.querySelector('#cable-hint').textContent=pending?`Connecting from ${name(s,pending)} — choose an input jack. Escape cancels.`:'Click an output jack › then an input jack ‹ to connect. Multiple cables split or sum automatically.';
  }
  function controls(s){const list=nodes(s);return `<h2>Patch cables</h2><p>Connect any output to one or more inputs. Joining cables sums their signals. Wiring is shared by all four scenes. Feedback loops are not supported.</p><div class="cable-form"><label>From<select id="cable-from">${list.filter(b=>b.id!=='output').map(b=>`<option value="${b.id}">${esc(name(s,b.id))}</option>`).join('')}</select></label><label>To<select id="cable-to">${list.filter(b=>b.id!=='input').map(b=>`<option value="${b.id}">${esc(name(s,b.id))}</option>`).join('')}</select></label><button id="connect-cable" class="primary">Connect cable</button></div><div class="cable-list">${s.connections.map(([a,b],i)=>`<div><span>${esc(name(s,a))} → ${esc(name(s,b))}</span><button data-disconnect="${i}" aria-label="Disconnect ${esc(name(s,a)+' to '+name(s,b))}">Disconnect</button></div>`).join('')||'<p>No cables yet.</p>'}</div>`;}
  function destination(e){const board=document.querySelector('.patch-board'),r=board.getBoundingClientRect();return {x:Math.max(0,Math.min(5000,Math.round(((e.clientX-r.left)/scale-65)/10)*10)),y:Math.max(0,Math.min(3000,Math.round(((e.clientY-r.top)/scale-78)/10)*10)),element:board,side:'drop-lane'};}
  return {render,controls,destination,name};
})();
