window.RoutingUI = (()=>{
  const R=GuitarRig;
  const labels={parallel:'Both paths / full range',blend:'A/B blend',crossover:'Frequency crossover'};
  function card(b,s,selected){
    const d=R.definition(b.key),v=s.scenes[s.scene][b.id];
    return `<button draggable="false" class="gear-block ${b.id===selected?'selected':''} ${v.on?'':'bypassed'}" data-block="${b.id}" style="--accent:${d.colour}" aria-label="Edit ${d.name} on ${R.laneNames[b.lane]}${v.on?'':', bypassed'}" aria-pressed="${b.id===selected}">${GearArt.svg(b.key,v.on)}<strong>${d.name}</strong><small><i class="gear-led"></i>${v.on?'ON':'BYPASSED'} · ${d.type==='Amps'?'NAM A2':d.type==='Cabs'?'CAB IR':d.type.toUpperCase()}</small></button>`;
  }
  function lane(s,id,selected,addLane){
    const blocks=R.blocksIn(s,id),isBranch=id==='a'||id==='b',route=s.routes[s.scene];
    let subtitle=id==='pre'?'INPUT → TOP TO BOTTOM':id==='post'?'TOP TO BOTTOM → OUTPUT':s.parallel&&route.mode==='crossover'?(id==='a'?`LOW · BELOW ${route.cross} Hz`:`HIGH · ABOVE ${route.cross} Hz`):'LEFT TO RIGHT';
    return `<section class="route-lane lane-${id} ${addLane===id?'add-target':''}" data-lane="${id}" aria-label="${R.laneNames[id]}"><header><span>${isBranch?`<b>${id.toUpperCase()}</b>`:''}${R.laneNames[id]}</span><small>${subtitle}</small></header><div class="lane-devices">${blocks.map(b=>card(b,s,selected)).join('')}${!blocks.length?`<span class="empty-path">${isBranch?'Dry signal passes through':'Direct connection'}<small>Drop a device here</small></span>`:''}<button class="lane-add" data-add-lane="${id}" aria-label="Add device to ${R.laneNames[id]}">＋</button></div>${isBranch&&s.parallel?`<footer>${route[id].mute?'MUTED':`${route[id].level} dB · ${route[id].pan===0?'CENTRE':Math.abs(route[id].pan)+(route[id].pan<0?' L':' R')}`}${route[id].invert?' · Ø INVERTED':''}</footer>`:''}</section>`;
  }
  function render(s,selected,addLane){
    const route=s.routes[s.scene];
    document.querySelector('#routing-bar').innerHTML=`<div class="routing-mode" role="group" aria-label="Routing topology"><button data-topology="serial" class="${!s.parallel?'active':''}" aria-pressed="${!s.parallel}">→ Serial</button><button data-topology="parallel" class="${s.parallel?'active':''}" aria-pressed="${s.parallel}">⑂ Parallel A / B</button></div><div class="route-actions"><span>Adding to <b>${R.laneNames[addLane]}</b></span><button id="dual-template" class="quiet">Load dual-amp example</button><button id="route-controls" class="quiet">${s.parallel?'Split & mixer':'Output controls'} ↗</button></div>`;
    document.querySelector('#chain').innerHTML=`<div class="routing-canvas ${s.parallel?'parallel':'serial'}"><div class="shared-stage"><span class="io-port">◎ GUITAR IN</span>${lane(s,'pre',selected,addLane)}</div><div class="junction split ${s.parallel?'':'straight'}"><div class="junction-wires"></div><button data-route-panel="split" aria-label="Edit splitter"><span>${s.parallel?'⑂':'→'}</span><strong>${s.parallel?'SPLIT':'SEND'}</strong><small>${s.parallel?(route.mode==='crossover'?'LOW / HIGH':route.mode==='blend'?`${100-route.blend} / ${route.blend}`:'A + B'):'PATH A'}</small></button></div><div class="branch-bank">${lane(s,'a',selected,addLane)}${s.parallel?lane(s,'b',selected,addLane):''}</div><div class="junction merge ${s.parallel?'':'straight'}"><div class="junction-wires"></div><button data-route-panel="mix" aria-label="Edit merge mixer"><span>⋈</span><strong>${s.parallel?'MERGE':'LEVEL'}</strong><small>${s.parallel?'STEREO MIX':'PATH A'}</small></button></div><div class="shared-stage">${lane(s,'post',selected,addLane)}<span class="io-port">◎ STEREO OUT</span></div></div>`;
    document.querySelector('#routing-summary').textContent=s.parallel?`Pre → ${labels[route.mode]} → Merge → Post`:'Pre → Path A → Post';
  }
  function controls(s){
    const r=s.routes[s.scene];
    return `<h2>${s.parallel?'Two paths. One sound.':'Shape the output.'}</h2><p class="route-explainer">${s.parallel?'The input passes through the shared pedals, splits into A and B, then combines before the shared output effects.':'A single path connects the shared input and output chains.'} Settings below belong to the <strong>${R.sceneNames[s.scene]}</strong> scene.</p>${s.parallel?`<label>Split mode<select data-route="mode" aria-label="Split mode">${Object.entries(labels).map(([v,label])=>`<option value="${v}" ${r.mode===v?'selected':''}>${label}</option>`).join('')}</select></label><div id="split-extra">${splitExtra(r)}</div>`:''}<div class="mixer-strips">${(s.parallel?['a','b']:['a']).map(l=>`<section class="mixer-strip"><h3><b>${l.toUpperCase()}</b> ${R.laneNames[l]}</h3><label>Level <span>dB</span><input data-route="${l}.level" aria-label="Path ${l.toUpperCase()} level" type="number" min="-60" max="6" step="0.5" value="${r[l].level}"></label><label>Pan <span>−100 L / +100 R</span><input data-route="${l}.pan" aria-label="Path ${l.toUpperCase()} pan" type="range" min="-100" max="100" step="1" value="${r[l].pan}"><output>${r[l].pan===0?'Centre':Math.abs(r[l].pan)+(r[l].pan<0?' L':' R')}</output></label><div class="mixer-toggles"><label><input type="checkbox" data-route="${l}.mute" ${r[l].mute?'checked':''}>Mute</label><label><input type="checkbox" data-route="${l}.invert" ${r[l].invert?'checked':''}>Ø Invert</label></div></section>`).join('')}</div><p class="route-footnote">Routing design only · No sound is processed yet. Parallel levels default to −6 dB per path to leave room when summed. Empty paths pass signal through.</p>`;
  }
  function splitExtra(r){
    if(r.mode==='crossover')return `<label>Crossover frequency · A low / B high<input data-route="cross" type="number" aria-label="Crossover frequency" min="40" max="5000" step="1" value="${r.cross}"></label><p class="route-hint">Hz · Filter implementation and phase alignment come with the audio engine.</p>`;
    if(r.mode==='blend')return `<label>A / B blend<input data-route="blend" type="range" aria-label="A B blend" min="0" max="100" value="${r.blend}"><output>${100-r.blend}% A / ${r.blend}% B</output></label><p class="route-hint">Linear split weights before the path level controls.</p>`;
    return '<p class="route-hint">Send the full input to both paths. Use the mixer to balance their outputs.</p>';
  }
  return {render,controls,splitExtra};
})();

